version: '3.8'

networks:
  ml_monitoring:
    driver: bridge

services:
  etcd:
    container_name: milvus-etcd
    restart: always
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./yappy_dublicate_services/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - ml_monitoring

  minio:
    container_name: milvus-minio
    restart: always
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    expose:
      - 9001
    volumes:
      - ./yappy_dublicate_services/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    ports:
      - 9001:9001
      - 9000:9000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ml_monitoring

  milvus-standalone:
    container_name: milvus-standalone
    restart: always
    image: milvusdb/milvus:v2.4.11
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./yappy_dublicate_services/volumes/milvus:/var/lib/milvus
    ports:
      - 19530:19530
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - ml_monitoring

  app_backend:
    build: .
    restart: always
    container_name: preprod
    command: python main.py
    volumes:
      - ./configs:/app/configs
      - ./swagger.yaml:/app/swagger.yaml
    ports:
      - 8000:8000
    networks:
      - ml_monitoring
    depends_on:
      - milvus-standalone
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]