# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  delete_file_mp4 : False  # Удялять ли файлы mp4 после их обработки

#--------------------------------------------------GENERAL--------------------------------------------------

general:
  video_folder: videos
  swagger_pth: swagger.yaml
  fastapi_port: 8000
  

# ------------------------------------------------- NODES --------------------------------------------------

video_embedding_node:
  model_pth: test.pt


