# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  delete_file_mp4 : False  # Удялять ли файлы mp4 после их обработки

#--------------------------------------------------GENERAL--------------------------------------------------

general:
  video_folder: videos
  swagger_pth: swagger.yaml
  fastapi_port: 8000
  

# ------------------------------------------------- NODES --------------------------------------------------

video_embedding_node:
  model_pth: test.pt

VectorDBNode:
  collection_name: "demo_collection"
  dimension: 5
  cosine_distance_treshold: 0.1
  metric_type: "COSINE"
  host: milvus-standalone
  port: 19530
  drop_db: False