# ----------------------------------------------- PIPELINE -------------------------------------------------

pipeline:
  delete_file_mp4 : True  # Удялять ли файлы mp4 после их обработки

#--------------------------------------------------GENERAL--------------------------------------------------

general:
  video_folder: videos
  swagger_pth: swagger.yaml
  fastapi_port: 8000
  

# ------------------------------------------------- NODES --------------------------------------------------

video_embedding_node:
  embeding_method: "mvit"
  resnet_fifty:
    # model_pth: test.pt
    model_name: "slowfast_r50" 
    frames_per_second: 30
    sampling_rate: 2
    num_frames: 32
    crop_size: 256
    side_size: 256
  mvit:
    # model_pth: test.pt
    model_name: "mvit_base_32x3" 
    frames_per_second: 30
    sampling_rate: 2
    num_frames: 32
    crop_size: 224
    side_size: 224

VectorDBNode:
  collection_name: "demo_collection_2"
  dimension: 400
  cosine_distance_treshold: 0.6
  metric_type: "COSINE"
  host: milvus-standalone
  port: 19530
  drop_db: True